trigger: 
- main

pool: 
   vmImage: ubuntu-latest
steps:
- task: CopyFiles@2
  displayName: 'Copy distribution to artifact staging directory'
  inputs:
    sourceFolder: 'account'
    targetFolder: '$(Build.ArtifactStagingDirectory)/account'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'account'
    publishLocation: 'Container'


