trigger: 
- main

pool: 
   vmImage: ubuntu-latest

jobs:
- deployment: VMDeploy
  displayName: test
  environment: 
   name: test
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: touch abc
            - task: CopyFilesOverSSH@0
              inputs:
                sshEndpoint: 'HW ECS1'
                contents: '**'
                readyTimeout: '20000'


