trigger: 
- main

pool: 
   vmImage: ubuntu-latest


steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'HW ECS1'
    sourceFolder: azure-pipelines.yml
    contents: '**'
    readyTimeout: '20000'

